apiVersion: v1
kind: Service
metadata:
  name: knutt-vs-muschel-web
  namespace: knutt-vs-muschel
  labels:
    app.kubernetes.io/name: knutt-vs-muschel
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: knutt-vs-muschel
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
